import "./src/header/header.js"
import "./src/body/body.js"
import "./src/body/body.scss"
import "./src/header/header.scss"
import "./src/components/funciones.js"
import "./src/components/variables.scss"
